In [ ]:
import numpy as np
data=np.array([23.8,23,56,44,34,23,48])
first_week=data[:8]
fourth_week=data[24:31]
print(first_week)
print(fourth_week)

In [4]:
data=np.array([23.8,23,56,44,34,23,48])
data_above_30=data[data>30]
print(data_above_30)

[56. 44. 34. 48.]


In [5]:
import numpy as np

In [15]:
arr_1 = np.array([10,20,10,30,11,78,88,100,12,12,89,69])


In [17]:
print (arr_1.reshape(4,3))

[[ 10  20  10]
 [ 30  11  78]
 [ 88 100  12]
 [ 12  89  69]]


In [11]:
arr_2 = np.array([10,21,45,65,66,75,23,14,25,36,47,58])
print(arr_2)

[10 21 45 65 66 75 23 14 25 36 47 58]


In [16]:
print (np.vstack((arr_1,arr_2)))

[[ 10  20  10  30  11  78  88 100  12  12  89  69]
 [ 10  21  45  65  66  75  23  14  25  36  47  58]]


In [18]:
arr_1.reshape(3,4).T

array([[ 10,  11,  12],
       [ 20,  78,  12],
       [ 10,  88,  89],
       [ 30, 100,  69]])