In [1]:
import numpy as np
import random

In [3]:
student_data = np.random.randint(10,20,(10,5))
print(  student_data )

[[17 10 15 14 10]
 [13 16 10 11 19]
 [12 12 11 16 17]
 [12 14 18 19 18]
 [18 17 12 13 18]
 [12 14 11 16 18]
 [12 18 13 12 15]
 [12 19 14 16 11]
 [18 16 16 18 11]
 [10 16 10 19 10]]


In [11]:
student_avg  = student_data.mean(axis=1)
avg = np.mean(student_data,axis=1)
print( avg )
print(  student_avg )

[13.2 13.8 13.6 16.2 15.6 14.2 14.  14.4 15.8 13. ]
[13.2 13.8 13.6 16.2 15.6 14.2 14.  14.4 15.8 13. ]
